name: API Tests
on: [pull_request]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - run: pip install ruff
      - run: ruff check .

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Docker Setup Compose
        uses: docker/setup-compose-action@v1.2.0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Create .env file
        run: |
          cat << 'EOF' > .env
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB_AUTH=${{ secrets.POSTGRES_DB_AUTH }}
          POSTGRES_DB_UNIVERSITY=${{ secrets.POSTGRES_DB_UNIVERSITY }}
          AUTH_SERVICE_INTERNAL_URL=${{ secrets.AUTH_SERVICE_INTERNAL_URL }}
          AUTH_SERVICE_API_URL=${{ secrets.AUTH_SERVICE_API_URL }}
          UNIVERSITY_SERVICE_INTERNAL_URL=${{ secrets.UNIVERSITY_SERVICE_INTERNAL_URL }}
          UNIVERSITY_SERVICE_API_URL=${{ secrets.UNIVERSITY_SERVICE_API_URL }}
          EOF
        shell: bash
      - run: docker compose up -d
      - run: docker build -t api-tests .
      - run: docker run --network host api-tests
      - name: Prepare report data
        run: |
          docker run --rm \
                 -v $(pwd)/allure-results:/api_framework/allure-results \
                 -v $(pwd)/allure-report:/api_framework/allure-report \
                 api-tests \
                 allure generate allure-results -o allure-report --clean
      - uses: actions/upload-pages-artifact@v3.0.1
        with:
          name: github-pages
          path: ./allure-report

  allure-report:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4.3.0
        with:
          name: allure-report
          path: ./allure-report
      - uses: actions/deploy-pages@v4.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
