name: API Tests
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - run: pip install ruff
      - run: ruff check .

  test:
    needs: lint 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Docker Setup Compose
        uses: docker/setup-compose-action@v1.2.0
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Create .env file
        run: |
          cat << 'EOF' > .env
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          API_KEY=${{ secrets.API_SECRET }}
          DEBUG_MODE=false
          EOF
        shell: bash
      
      - run: pip install pytest
      - run: docker compose up -d
      - run: docker build -t api-tests .
      - run: docker run --network host api-tests
